"""Original educational scenarios. Not labelled real-world news or a validated test."""
MISSIONS=[
 {'title':'Logo resmi, tautan asing','skill':'Periksa sumber','art':'briefcase','scenario':'Sebuah poster lowongan memakai logo perusahaan. Formulir pendaftarannya ada di domain lain dan meminta nomor Telegram. Kamu belum menemukan pengumuman di kanal resmi.','options':['Isi dulu agar tidak kehabisan kuota.','Buka kanal karier resmi secara mandiri dan cocokkan lowongannya.','Simpulkan semua lowongan daring pasti palsu.'],'correct':1,'explanation':'Logo bisa disalin. Cocokkan pengumuman serta domain dengan kanal resmi; jangan menyerahkan data hanya karena poster terlihat profesional.','url':'https://turnbackhoax.id/articles/37052-penipuan-tautan-lowongan-kerja-kawasaki-motor'},
 {'title':'Viral bukan berarti valid','skill':'Bukti vs popularitas','art':'chat','scenario':'Temanmu menunjukkan pesan yang sudah dibagikan ribuan kali. Pesan itu tidak mencantumkan sumber atau tanggal.','options':['Cari asal pesan, tanggal, dan bukti yang mendukungnya.','Percaya karena ribuan orang tidak mungkin keliru.','Tetapkan pesan palsu hanya karena tanpa tanggal.'],'correct':0,'explanation':'Popularitas menunjukkan penyebaran, bukan kebenaran. Kekurangan sumber adalah alasan untuk memeriksa lebih lanjut, bukan bukti tunggal bahwa klaim salah.','url':'https://cekfakta.com/about'},
 {'title':'Judul keras, isi membantah','skill':'Baca konteks','art':'grain','scenario':'Judul menyebut tuduhan sensasional. Di dalam artikel, penulis mengutip tuduhan itu lalu menunjukkan bukti yang membantahnya.','options':['Labeli artikel dari judulnya saja.','Anggap penulis mendukung setiap kutipan.','Bedakan klaim yang dikutip dari kesimpulan penulis.'],'correct':2,'explanation':'Artikel pemeriksaan bisa memuat kutipan klaim salah. Label untuk klaim tidak otomatis sama dengan penilaian terhadap artikel yang membantahnya.','url':'https://turnbackhoax.id/articles/3304-salah-video-produksi-beras-plastik'},
 {'title':'Sudah resmi atau masih rencana?','skill':'Ketepatan status','art':'school','scenario':'Sumber menyatakan program masih disiapkan. Sebuah unggahan mengubahnya menjadi pengumuman bahwa program sudah berlaku di dua kampus.','options':['Anggap sama karena membahas program yang sama.','Cek apakah sudah ada keputusan resmi, kapan berlaku, dan siapa pesertanya.','Abaikan tanggal karena kebijakannya pasti tetap.'],'correct':1,'explanation':'Rencana dan keputusan yang berlaku berbeda. Status, peserta, dan tanggal harus cocok dengan dokumen resmi pada waktu klaim dibuat.','url':'https://turnbackhoax.id/articles/37049-salah-undip-dan-unpad-jadi-peserta-perdana-program-pendidikan-gratis-prabowo'},
 {'title':'AI setuju. Sudah cukup?','skill':'Literasi AI','art':'hero','scenario':'Model memprediksi artikel sebagai Valid. Kamu belum membaca sumbernya dan tidak tahu bukti yang dipakai penulis.','options':['Bagikan karena AI telah memeriksa semua fakta.','Ubah label manual supaya sesuai harapan.','Periksa sumber dan bukti meskipun model tampak meyakinkan.'],'correct':2,'explanation':'SVM mengklasifikasikan pola teks. Prediksi bukan penelusuran bukti; kesepakatan manusia dan model belum membuktikan sebuah klaim.','url':'https://scikit-learn.org/stable/modules/svm.html'},
 {'title':'Lima situs, satu sumber','skill':'Kemandirian sumber','art':'chat','scenario':'Lima situs memuat kabar serupa. Setelah dibuka, semuanya menyalin satu unggahan tanpa bukti tambahan.','options':['Cari sumber asal dan konfirmasi yang benar-benar independen.','Hitung sebagai lima bukti yang berbeda.','Percaya pada situs dengan desain paling rapi.'],'correct':0,'explanation':'Pengulangan tidak sama dengan konfirmasi independen. Telusuri asal informasi dan bukti tambahan yang tidak sekadar menyalin sumber yang sama.','url':'https://cekfakta.com/about'},
 {'title':'Gambar sama, cerita berbeda','skill':'Konteks visual','art':'grain','scenario':'Sebuah video lama dibagikan dengan narasi kejadian baru. Kamu hanya melihat cuplikan tanpa lokasi dan waktu yang jelas.','options':['Percaya karena videonya nyata.','Cari unggahan awal, lokasi, dan waktu sebelum mengaitkannya dengan kejadian baru.','Anggap semua video lama adalah hasil AI.'],'correct':1,'explanation':'Video autentik dapat diberi konteks yang salah. Keaslian gambar dan ketepatan narasi merupakan dua hal yang perlu diperiksa terpisah.','url':'https://turnbackhoax.id/articles/3304-salah-video-produksi-beras-plastik'},
 {'title':'Tidak ditemukan bukan berarti benar','skill':'Batas pencarian','art':'plant','scenario':'Kamu mencari klaim tentang bantuan pertanian di koleksi TELISIK, tetapi hasilnya kosong. Koleksi hanya berisi beberapa kasus.','options':['Klaim pasti benar karena belum pernah dibantah.','Klaim pasti palsu karena tidak ditemukan.','Tunda kesimpulan dan periksa kanal resmi serta sumber lain.'],'correct':2,'explanation':'Koleksi terbatas tidak mencakup semua informasi. Hasil pencarian kosong berarti belum ada rujukan yang cocok, bukan keputusan benar atau salah.','url':'https://turnbackhoax.id/articles/30582'}
]
